# Generated by Django 3.2.9 on 2021-11-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinbaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('order_id', models.CharField(default='', max_length=50)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='nft_10_price',
            field=models.FloatField(blank=True, help_text='use . not ,', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_10_image',
            field=models.ImageField(blank=True, help_text='you can add how many nft you want up tp 20', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_10_price',
            field=models.FloatField(blank=True, help_text='use . not ,', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_10_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_11_image',
            field=models.ImageField(blank=True, help_text='you can add how many nft you want up tp 20', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_11_price',
            field=models.FloatField(blank=True, help_text='use . not ,', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_11_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_12_image',
            field=models.ImageField(blank=True, help_text='you can add how many nft you want up tp 20', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_12_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_13_price',
            field=models.FloatField(blank=True, help_text='use . not ,', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_13_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_14_image',
            field=models.ImageField(blank=True, help_text='you can add how many nft you want up tp 20', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_14_price',
            field=models.FloatField(blank=True, help_text='use . not ,', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_15_image',
            field=models.ImageField(blank=True, help_text='you can add how many nft you want up tp 20', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_15_price',
            field=models.FloatField(blank=True, help_text='use . not ,', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_15_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_16_image',
            field=models.ImageField(blank=True, help_text='you can add how many nft you want up tp 20', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_16_price',
            field=models.FloatField(blank=True, help_text='use . not ,', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_16_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_17_image',
            field=models.ImageField(blank=True, help_text='you can add how many nft you want up tp 20', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_17_price',
            field=models.FloatField(blank=True, help_text='use . not ,', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_17_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_18_image',
            field=models.ImageField(blank=True, help_text='you can add how many nft you want up tp 20', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_18_price',
            field=models.FloatField(blank=True, help_text='use . not ,', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_18_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_1_image',
            field=models.ImageField(blank=True, help_text='you can add how many nft you want up tp 20', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_1_price',
            field=models.FloatField(blank=True, help_text='use . not ,', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_1_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_2_image',
            field=models.ImageField(blank=True, help_text='you can add how many nft you want up tp 20', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_2_price',
            field=models.FloatField(blank=True, help_text='use . not ,', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_2_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_3_image',
            field=models.ImageField(blank=True, help_text='you can add how many nft you want up tp 20', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_3_price',
            field=models.FloatField(blank=True, help_text='use . not ,', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_3_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_4_image',
            field=models.ImageField(blank=True, help_text='you can add how many nft you want up tp 20', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_4_price',
            field=models.FloatField(blank=True, help_text='use . not ,', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_4_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_5_image',
            field=models.ImageField(blank=True, help_text='you can add how many nft you want up tp 20', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_5_price',
            field=models.FloatField(blank=True, help_text='use . not ,', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_5_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_6_image',
            field=models.ImageField(blank=True, help_text='you can add how many nft you want up tp 20', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_6_price',
            field=models.FloatField(blank=True, help_text='use . not ,', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_6_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_7_image',
            field=models.ImageField(blank=True, help_text='you can add how many nft you want up tp 20', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_7_price',
            field=models.FloatField(blank=True, help_text='use . not ,', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_7_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_8_image',
            field=models.ImageField(blank=True, help_text='you can add how many nft you want up tp 20', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_8_price',
            field=models.FloatField(blank=True, help_text='use . not ,', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_8_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_9_image',
            field=models.ImageField(blank=True, help_text='you can add how many nft you want up tp 20', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_9_price',
            field=models.FloatField(blank=True, help_text='use . not ,', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nft_9_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
