from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save


class CoinbaseOrder(models.Model):
    value    = models.FloatField(default=0)
    order_id = models.CharField(max_length=50, default="")
    used     = models.BooleanField(default=False)


class case(models.Model):
    case_title= models.CharField(max_length=200)
    case_price=models.FloatField(help_text = "use . not ,",blank=False)
    case_photo= models.ImageField(blank=False )
    nft_1_title= models.CharField(max_length=200,null=True)
    nft_1_image= models.ImageField(help_text="you can add how many nft you want up tp 20",null=True)
    nft_1_price=models.FloatField(help_text = "use . not ,",null=True)
    nft_1_percentage=models.FloatField(help_text = "use . not ,",null=True)
    nft_2_title= models.CharField(max_length=200,blank=True,null=True)
    nft_2_image= models.ImageField(blank=True ,help_text="you can add how many nft you want up tp 20",null=True)
    nft_2_price=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_2_percentage=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_3_title= models.CharField(max_length=200,blank=True,null=True)
    nft_3_image= models.ImageField(blank=True ,help_text="you can add how many nft you want up tp 20",null=True)
    nft_3_price=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_3_percentage=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_4_title= models.CharField(max_length=200,blank=True,null=True)
    nft_4_image= models.ImageField(blank=True ,help_text="you can add how many nft you want up tp 20",null=True)
    nft_4_price=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_4_percentage=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_5_title= models.CharField(max_length=200,blank=True,null=True)
    nft_5_image= models.ImageField(blank=True ,help_text="you can add how many nft you want up tp 20",null=True)
    nft_5_price=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_5_percentage=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_6_title= models.CharField(max_length=200,blank=True,null=True)
    nft_6_image= models.ImageField(blank=True ,help_text="you can add how many nft you want up tp 20",null=True)
    nft_6_price=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_6_percentage=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_7_title= models.CharField(max_length=200,blank=True,null=True)
    nft_7_image= models.ImageField(blank=True ,help_text="you can add how many nft you want up tp 20",null=True)
    nft_7_price=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_7_percentage=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_8_title= models.CharField(max_length=200,blank=True,null=True)
    nft_8_image= models.ImageField(blank=True ,help_text="you can add how many nft you want up tp 20",null=True)
    nft_8_price=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_8_percentage=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_9_title= models.CharField(max_length=200,blank=True,null=True)
    nft_9_image= models.ImageField(blank=True ,help_text="you can add how many nft you want up tp 20",null=True)
    nft_9_price=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_9_percentage=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_10_title= models.CharField(max_length=200,blank=True,null=True)
    nft_10_image= models.ImageField(blank=True ,help_text="you can add how many nft you want up tp 20",null=True)
    nft_10_price=models.FloatField(help_text = "use . not ,",null=True,blank=True)
    nft_10_percentage=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_11_title= models.CharField(max_length=200,blank=True,null=True)
    nft_11_image= models.ImageField(blank=True ,help_text="you can add how many nft you want up tp 20",null=True)
    nft_11_price=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_12_percentage=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_12_title= models.CharField(max_length=200,blank=True,null=True)
    nft_12_image= models.ImageField(blank=True ,help_text="you can add how many nft you want up tp 20",null=True)
    nft_13_price=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_13_percentage=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_13_title= models.CharField(max_length=200,blank=True,null=True)
    nft_14_image= models.ImageField(blank=True ,help_text="you can add how many nft you want up tp 20",null=True)
    nft_14_price=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_14_percentage=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_15_title= models.CharField(max_length=200,blank=True,null=True)
    nft_15_image= models.ImageField(blank=True ,help_text="you can add how many nft you want up tp 20",null=True)
    nft_15_price=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_15_percentage=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_16_title= models.CharField(max_length=200,blank=True,null=True)
    nft_16_image= models.ImageField(blank=True ,help_text="you can add how many nft you want up tp 20",null=True)
    nft_16_price=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_16_percentage=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_17_title= models.CharField(max_length=200,blank=True,null=True)
    nft_17_image= models.ImageField(blank=True ,help_text="you can add how many nft you want up tp 20",null=True)
    nft_17_price=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_17_percentage=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_18_title= models.CharField(max_length=200,blank=True,null=True)
    nft_18_image= models.ImageField(blank=True ,help_text="you can add how many nft you want up tp 20",null=True)
    nft_18_price=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_18_percentage=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_19_title= models.CharField(max_length=200,blank=True,null=True)
    nft_19_image= models.ImageField(blank=True ,help_text="you can add how many nft you want up tp 20",null=True)
    nft_19_price=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_20_percentage=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_20_title= models.CharField(max_length=200,blank=True,null=True)
    nft_20_image= models.ImageField(blank=True ,help_text="you can add how many nft you want up tp 20",null=True)
    nft_20_price=models.FloatField(help_text = "use . not ,",blank=True,null=True)
    nft_20_percentage=models.FloatField(help_text = "use . not ,",blank=True,null=True)

    def __str__(self):
        return self.case_title 

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    balance=models.FloatField(default=0,blank=True)
    nft_1_title= models.CharField(max_length=200,null=True,blank=True)
    nft_1_image= models.ImageField(help_text="you can add how many nft you want up tp 20",null=True,blank=True)
    nft_1_price=models.FloatField(help_text = "use . not ,",null=True,blank=True)
    nft_2_title= models.CharField(max_length=200,null=True,blank=True)
    nft_2_image= models.ImageField(help_text="you can add how many nft you want up tp 20",null=True,blank=True)
    nft_2_price=models.FloatField(help_text = "use . not ,",null=True,blank=True)
    nft_3_title= models.CharField(max_length=200,null=True,blank=True)
    nft_3_image= models.ImageField(help_text="you can add how many nft you want up tp 20",null=True,blank=True)
    nft_3_price=models.FloatField(help_text = "use . not ,",null=True,blank=True)
    nft_4_title= models.CharField(max_length=200,null=True,blank=True)
    nft_4_image= models.ImageField(help_text="you can add how many nft you want up tp 20",null=True,blank=True)
    nft_4_price=models.FloatField(help_text = "use . not ,",null=True,blank=True)
    nft_5_title= models.CharField(max_length=200,null=True,blank=True)
    nft_5_image= models.ImageField(help_text="you can add how many nft you want up tp 20",null=True,blank=True)
    nft_5_price=models.FloatField(help_text = "use . not ,",null=True,blank=True)
    nft_6_title= models.CharField(max_length=200,null=True,blank=True)
    nft_6_image= models.ImageField(help_text="you can add how many nft you want up tp 20",null=True,blank=True)
    nft_6_price=models.FloatField(help_text = "use . not ,",null=True,blank=True)
    nft_7_title= models.CharField(max_length=200,null=True,blank=True)
    nft_7_image= models.ImageField(help_text="you can add how many nft you want up tp 20",null=True,blank=True)
    nft_7_price=models.FloatField(help_text = "use . not ,",null=True,blank=True)
    nft_8_title= models.CharField(max_length=200,null=True,blank=True)
    nft_8_image= models.ImageField(help_text="you can add how many nft you want up tp 20",null=True,blank=True)
    nft_8_price=models.FloatField(help_text = "use . not ,",null=True,blank=True)
    nft_9_title= models.CharField(max_length=200,null=True,blank=True)
    nft_9_image= models.ImageField(help_text="you can add how many nft you want up tp 20",null=True,blank=True)
    nft_9_price=models.FloatField(help_text = "use . not ,",null=True,blank=True)
    nft_10_title= models.CharField(max_length=200,null=True,blank=True)
    nft_10_image= models.ImageField(help_text="you can add how many nft you want up tp 20",null=True,blank=True)
    nft_10_price=models.FloatField(help_text = "use . not ,",null=True,blank=True)
    nft_11_title= models.CharField(max_length=200,null=True,blank=True)
    nft_11_image= models.ImageField(help_text="you can add how many nft you want up tp 20",null=True,blank=True)
    nft_11_price=models.FloatField(help_text = "use . not ,",null=True,blank=True)
    nft_12_title= models.CharField(max_length=200,null=True,blank=True)
    nft_12_image= models.ImageField(help_text="you can add how many nft you want up tp 20",null=True,blank=True)
    nft_13_price=models.FloatField(help_text = "use . not ,",null=True,blank=True)
    nft_13_title= models.CharField(max_length=200,null=True,blank=True)
    nft_14_image= models.ImageField(help_text="you can add how many nft you want up tp 20",null=True,blank=True)
    nft_14_price=models.FloatField(help_text = "use . not ,",null=True,blank=True)
    nft_15_title= models.CharField(max_length=200,null=True,blank=True)
    nft_15_image= models.ImageField(help_text="you can add how many nft you want up tp 20",null=True,blank=True)
    nft_15_price=models.FloatField(help_text = "use . not ,",null=True,blank=True)
    nft_16_title= models.CharField(max_length=200,null=True,blank=True)
    nft_16_image= models.ImageField(help_text="you can add how many nft you want up tp 20",null=True,blank=True)
    nft_16_price=models.FloatField(help_text = "use . not ,",null=True,blank=True)
    nft_17_title= models.CharField(max_length=200,null=True,blank=True)
    nft_17_image= models.ImageField(help_text="you can add how many nft you want up tp 20",null=True,blank=True)
    nft_17_price=models.FloatField(help_text = "use . not ,",null=True,blank=True)
    nft_18_title= models.CharField(max_length=200,null=True,blank=True)
    nft_18_image= models.ImageField(help_text="you can add how many nft you want up tp 20",null=True,blank=True)
    nft_18_price=models.FloatField(help_text = "use . not ,",null=True,blank=True)
    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

